"""
Cookie 管理器模块
支持 Cookie 测试和集成到 yt-dlp
"""
import tempfile
from pathlib import Path
from typing import Optional, Dict
import subprocess
import json

from core.logger import get_logger

logger = get_logger()


class CookieManager:
    """Cookie 管理器
    
    负责 Cookie 的测试和管理，支持将 Cookie 字符串转换为 yt-dlp 可用的格式
    """
    
    def __init__(self, cookie_string: str = "", yt_dlp_path: str = "yt-dlp"):
        """初始化 Cookie 管理器
        
        Args:
            cookie_string: Cookie 字符串（浏览器复制的格式）
            yt_dlp_path: yt-dlp 可执行文件路径
        """
        self.cookie_string = cookie_string.strip()
        self.yt_dlp_path = yt_dlp_path
        self._temp_cookie_file: Optional[Path] = None
    
    def _cookie_string_to_netscape_file(self, cookie_string: str) -> Optional[Path]:
        """将 Cookie 字符串转换为 Netscape 格式文件
        
        Args:
            cookie_string: Cookie 字符串（浏览器格式）
        
        Returns:
            临时文件路径，如果转换失败则返回 None
        """
        if not cookie_string:
            return None
        
        try:
            # 创建临时文件
            temp_file = tempfile.NamedTemporaryFile(
                mode='w',
                suffix='.txt',
                delete=False,
                encoding='utf-8'
            )
            temp_path = Path(temp_file.name)
            
            # 写入 Netscape Cookie 文件头
            temp_file.write("# Netscape HTTP Cookie File\n")
            temp_file.write("# This file was generated by yt-subtitle-v2\n\n")
            
            # 解析 Cookie 字符串（格式：key1=value1; key2=value2; ...）
            cookies = {}
            for item in cookie_string.split(';'):
                item = item.strip()
                if not item:
                    continue
                if '=' in item:
                    key, value = item.split('=', 1)
                    key = key.strip()
                    value = value.strip()
                    if key:  # 确保 key 不为空
                        cookies[key] = value
                else:
                    # 如果单个项目没有 '='，可能是格式错误，记录警告但继续
                    logger.warning_i18n("cookie_format_invalid", preview=item[:50])
            
            # 检查是否解析到了 Cookie
            if not cookies:
                logger.error_i18n("cookie_string_empty")
                temp_file.close()
                temp_path.unlink()  # 删除空文件
                return None
            
            # 写入 Cookie（Netscape 格式）
            # Netscape 格式：domain, flag, path, secure, expiration, name, value
            # domain: 域名（.youtube.com 表示所有 youtube.com 子域）
            # flag: TRUE 表示所有主机都可以访问，FALSE 表示只有完全匹配的域名
            # path: Cookie 路径（/ 表示所有路径）
            # secure: TRUE 表示只在 HTTPS 连接中发送，FALSE 表示 HTTP 和 HTTPS 都可以
            # expiration: 过期时间（Unix 时间戳，0 表示会话 Cookie）
            # name: Cookie 名称
            # value: Cookie 值
            
            # 重要：YouTube 需要特定的 Cookie，特别是 __Secure-* 和 __Host-* 前缀的 Cookie
            # 这些 Cookie 需要正确的域名和 secure 标志
            for key, value in cookies.items():
                # 判断是否为安全 Cookie（__Secure- 或 __Host- 前缀）
                is_secure = key.startswith("__Secure-") or key.startswith("__Host-")
                
                # 对于安全 Cookie，使用 youtube.com 而不是 .youtube.com
                # 对于普通 Cookie，使用 .youtube.com
                if is_secure:
                    domain = "youtube.com"
                    secure_flag = "TRUE"
                else:
                    domain = ".youtube.com"
                    secure_flag = "TRUE"  # YouTube 现在主要使用 HTTPS
                
                # 写入 Netscape 格式：domain, flag, path, secure, expiration, name, value
                line = f"{domain}\tTRUE\t/\t{secure_flag}\t0\t{key}\t{value}\n"
                temp_file.write(line)
            
            logger.debug_i18n("cookies_written", count=len(cookies))
            
            temp_file.close()
            return temp_path
            
        except Exception as e:
            logger.error_i18n("cookie_convert_failed", error=str(e))
            return None
    
    def _extract_region_from_cookie(self) -> Optional[str]:
        """从 Cookie 字符串中提取地区信息
        
        尝试从 PREF Cookie 中提取 gl 参数（地区代码）
        PREF 格式通常为：f4=4000000&gl=US&hl=en 等
        
        Returns:
            地区代码（如 "US", "CN", "JP" 等），如果无法检测则返回 None
        """
        if not self.cookie_string:
            return None
        
        try:
            # 解析 Cookie 字符串，查找 PREF Cookie
            cookies = {}
            for item in self.cookie_string.split(';'):
                item = item.strip()
                if not item:
                    continue
                if '=' in item:
                    key, value = item.split('=', 1)
                    key = key.strip()
                    value = value.strip()
                    if key:
                        cookies[key] = value
            
            # 方法1：从 PREF Cookie 中提取 gl 参数
            pref_value = cookies.get("PREF", "")
            if pref_value:
                # 解析 PREF 值（URL 编码的参数格式）
                import urllib.parse
                params = urllib.parse.parse_qs(pref_value)
                
                # 查找 gl 参数（地区代码）
                gl_values = params.get("gl", [])
                if gl_values and len(gl_values) > 0:
                    region = gl_values[0].upper()  # 转换为大写（如 "us" -> "US"）
                    logger.info_i18n("cookie_region_extracted_pref", region=region)
                    return region
                else:
                    logger.debug_i18n("cookie_pref_no_gl")
            else:
                logger.debug_i18n("cookie_pref_not_found")
            
            # 方法2：尝试从其他可能的 Cookie 字段中提取地区信息
            # 检查是否有其他包含地区信息的 Cookie
            for key, value in cookies.items():
                key_upper = key.upper()
                if key_upper in ["GL", "LOCALE"]:
                    region = value.upper()
                    logger.info_i18n("cookie_region_extracted_field", key=key, region=region)
                    return region
                # 检查 hl 参数（语言代码，可能包含地区信息）
                elif key_upper == "HL" and len(value) >= 2:
                    # hl 格式可能是 "en-US", "zh-CN" 等，提取国家代码部分
                    if '-' in value:
                        region = value.split('-')[-1].upper()
                        logger.info_i18n("cookie_region_extracted_field", key=key, region=region)
                        return region
            
            logger.debug_i18n("cookie_region_extract_failed")
            return None
            
        except Exception as e:
            logger.warning_i18n("cookie_region_extract_failed", error=str(e))
            return None
    
    def get_cookie_file_path(self) -> Optional[str]:
        """获取 Cookie 文件路径（用于 yt-dlp --cookies 参数）
        
        Returns:
            Cookie 文件路径，如果没有 Cookie 则返回 None
        """
        if not self.cookie_string:
            logger.debug_i18n("cookie_string_empty_debug")
            return None
        
        # 如果已经有临时文件，直接返回
        if self._temp_cookie_file and self._temp_cookie_file.exists():
            logger.debug_i18n("cookie_file_exists", cookie_file=str(self._temp_cookie_file))
            return str(self._temp_cookie_file)
        
        # 创建新的临时文件
        self._temp_cookie_file = self._cookie_string_to_netscape_file(self.cookie_string)
        if self._temp_cookie_file:
            logger.info_i18n("cookie_file_created", cookie_file=str(self._temp_cookie_file))
            return str(self._temp_cookie_file)
        else:
            logger.warning_i18n("cookie_file_create_failed")
            return None
    
    def test_cookie(self, test_url: str = "https://www.youtube.com") -> Dict[str, any]:
        """测试 Cookie 是否可用
        
        Args:
            test_url: 测试 URL，默认使用 YouTube 首页
        
        Returns:
            测试结果字典：
            {
                "available": bool,  # Cookie 是否可用
                "region": Optional[str],  # 所在地区（如果可检测）
                "error": Optional[str],  # 错误信息（如果有）
                "details": Dict  # 详细信息
            }
        """
        if not self.cookie_string:
            return {
                "available": False,
                "region": None,
                "error": "未配置 Cookie",
                "details": {}
            }
        
        logger.info_i18n("cookie_test_start")
        
        try:
            # 获取 Cookie 文件路径
            cookie_file = self.get_cookie_file_path()
            if not cookie_file:
                from core.logger import translate_log
                error_msg = translate_log("cookie_file_create_failed")
                return {
                    "available": False,
                    "region": None,
                    "error": error_msg,
                    "details": {}
                }
            
            # 使用 yt-dlp 测试 Cookie
            # 尝试获取一个简单的视频信息（使用一个公开的测试视频）
            test_video_url = "https://www.youtube.com/watch?v=jNQXAC9IVRw"  # 一个公开的测试视频
            
            cmd = [
                self.yt_dlp_path,
                "--dump-json",
                "--no-warnings",
                "--cookies", cookie_file,
                test_video_url
            ]
            
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=30
            )
            
            if result.returncode != 0:
                error_msg = result.stderr[:200] if result.stderr else "未知错误"
                logger.warning_i18n("cookie_test_failed", error=error_msg)
                return {
                    "available": False,
                    "region": None,
                    "error": error_msg,
                    "details": {
                        "returncode": result.returncode,
                        "stderr": error_msg
                    }
                }
            
            # 解析 JSON 输出，尝试提取地区信息
            try:
                data = json.loads(result.stdout)
                region = self._extract_region_from_cookie()
                
                logger.info_i18n("cookie_test_success")
                if region:
                    logger.info_i18n("cookie_region_detected", region=region)
                
                return {
                    "available": True,
                    "region": region,
                    "error": None,
                    "details": {
                        "video_id": data.get("id"),
                        "title": data.get("title", "")[:50],
                        "channel": data.get("channel", "")
                    }
                }
                
            except json.JSONDecodeError as e:
                logger.warning_i18n("cookie_test_parse_failed", error=str(e))
                return {
                    "available": False,
                    "region": None,
                    "error": f"解析测试结果失败: {e}",
                    "details": {}
                }
                
        except subprocess.TimeoutExpired:
            logger.warning_i18n("cookie_test_timeout")
            return {
                "available": False,
                "region": None,
                "error": "测试超时",
                "details": {}
            }
        except Exception as e:
            logger.error_i18n("cookie_test_error", error=str(e))
            import traceback
            logger.debug(traceback.format_exc())
            return {
                "available": False,
                "region": None,
                "error": str(e),
                "details": {}
            }
    
    def cleanup(self):
        """清理临时文件"""
        if self._temp_cookie_file and self._temp_cookie_file.exists():
            try:
                self._temp_cookie_file.unlink()
                self._temp_cookie_file = None
            except Exception as e:
                logger.warning_i18n("cookie_temp_cleanup_failed", error=str(e))
    
    def __del__(self):
        """析构函数，清理临时文件"""
        self.cleanup()

